services:
  - type: web
    name: whisp-asr
    dockerfilePath: ./Dockerfile
    runtime: docker
    plan: free
    numInstances: 1
    envVars:
      - key: ANTHROPIC_API_KEY
        sync: false
    healthCheckPath: /
    autoDeploy: true
